
version: '3.10'
services:
  server:
    image: ml-project
    container_name: ml-project
    environment:
      - CHOKIDAR_USEPOLLING=true
    # restart: always
    build:
      context: ./ml_project
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./ml_project:/app/server

  ml-system:
    image: ml-system
    container_name: ml-system
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./ml-system
      dockerfile: Dockerfile
    expose: 
      - 50052
    ports:
      - 50052:50052
    volumes:
      - ./ml-system:/app/ml-system
    depends_on:
      - server
volumes:
  node_modules: